language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libasound2 libgconf-2-4 libgtk2.0-0 libnss3 libxss1 libxtst6 xvfb
script: npm run coveralls-with-xvfb